server:
  port: 9100

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    # prefer-ip-address: true
    # ip-address: 54.200.13.243
  client:
    serviceUrl:
      defaultZone: http://172.31.45.40:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: gateway

logging:
  level:
    com.example.howtodoinjava: DEBUG